spring:
  application:
    name: Notification
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false

      properties:
        spring.json.trusted.packages: notification.dto
        spring.json.value.default.type: notification.dto.VerifyEmailPayload
        spring.json.use.type.headers: false
      
  mail:
    host: ${SPRING_MAIL_HOST:127.0.0.1}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: ${SPRING_MAIL_SMTP_CONNECTION_TIMEOUT_MS:10000}
          timeout: ${SPRING_MAIL_SMTP_READ_TIMEOUT_MS:10000}
          writetimeout: ${SPRING_MAIL_SMTP_WRITE_TIMEOUT_MS:10000}
          starttls:
            enable: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/legal_notification}
    username: ${SPRING_DATASOURCE_USERNAME:legal_user}
    password: ${SPRING_DATASOURCE_PASSWORD:legal_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  mail:
    from: ${APP_MAIL_FROM:no-reply@localhost}
  notification-worker:
    fixed-delay-ms: ${APP_NOTIFICATION_WORKER_FIXED_DELAY_MS:15000}
    processing-timeout-seconds: ${APP_NOTIFICATION_WORKER_PROCESSING_TIMEOUT_SECONDS:120}
