CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_code VARCHAR(100) NOT NULL UNIQUE,
    client_user_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    assigned_to_user_id BIGINT,
    
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    client_name_snapshot VARCHAR(255),
    contact_snapshot TEXT,
    company_name_snapshot VARCHAR(255),
    client_revision_comment TEXT,
    client_revision_requested_at TIMESTAMP,
    revision_count INT NOT NULL DEFAULT 0,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_user_id) REFERENCES users(id),
    FOREIGN KEY (service_id) REFERENCES services(id),
    FOREIGN KEY (assigned_to_user_id) REFERENCES users(id)
);
