CREATE TABLE orders_comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    author_user_id BIGINT NOT NULL,
    comment_type VARCHAR(50) NOT NULL,
    body TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (author_user_id) REFERENCES users(id)
);
