ALTER TABLE users
    ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN email_verified_at TIMESTAMP NULL;

-- verification_codes:
-- хранит коды подтверждения для email verification и других чувствительных сценариев.
CREATE TABLE verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    channel VARCHAR(20) NOT NULL, -- Канал доставки кода, например EMAIL.
    purpose VARCHAR(50) NOT NULL, -- Бизнес-цель кода: VERIFY_EMAIL, CHANGE_PHONE, RESET_PASSWORD.
    recipient VARCHAR(255) NOT NULL, -- Куда реально отправляется код.
    code_hash VARCHAR(255) NOT NULL, -- Хэш кода, а не сам код в открытом виде.
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP NULL, -- Когда код был успешно использован.
    attempt_count INTEGER NOT NULL DEFAULT 0, -- Сколько раз пользователь уже пытался ввести код.
    max_attempts INTEGER NOT NULL DEFAULT 5, -- Максимум попыток до блокировки кода.
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_verification_codes_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Быстрый поиск кодов конкретного пользователя.
CREATE INDEX idx_verification_codes_user_id ON verification_codes(user_id);
-- Удобная фильтрация кодов по бизнес-назначению.
CREATE INDEX idx_verification_codes_purpose ON verification_codes(purpose);
-- Быстрый отбор истёкших и ещё активных кодов.
CREATE INDEX idx_verification_codes_expires_at ON verification_codes(expires_at);

-- outbox_events:
-- хранит события, которые auth-service должен надёжно отправить в брокер.
CREATE TABLE outbox_events (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(50) NOT NULL, -- Тип агрегата, которому принадлежит событие.
    aggregate_id VARCHAR(100) NOT NULL, -- Идентификатор агрегата в строковом виде.
    event_type VARCHAR(100) NOT NULL, -- Имя бизнес-события для публикации в брокер.
    payload JSONB NOT NULL, -- Полезная нагрузка события.
    status VARCHAR(20) NOT NULL, -- Текущее состояние публикации: NEW, PUBLISHED, FAILED.
    retry_count INTEGER NOT NULL DEFAULT 0, -- Сколько раз уже пытались публиковать событие.
    next_retry_at TIMESTAMP NULL, -- Когда можно делать следующую попытку публикации.
    last_error TEXT NULL, -- Последняя ошибка публикации, если она была.
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP NULL -- Когда событие было успешно отправлено в брокер.
);

-- Быстрый выбор новых и ожидающих публикации событий.
CREATE INDEX idx_outbox_events_status_created_at
    ON outbox_events(status, created_at);

-- Быстрый выбор событий, готовых к повторной отправке после retry.
CREATE INDEX idx_outbox_events_next_retry_at
    ON outbox_events(next_retry_at);
