/**
 * Central API catalog for the frontend.
 * Stored on window so api.html also works when opened directly from the filesystem.
 */
(function attachApiCatalog(global) {
  const IMPLEMENTED_API = [
    {
      method: "GET",
      path: "/api/services",
      access: "Public",
      status: "Implemented",
      purpose: "Возвращает список активных юридических услуг для сайта.",
      requestShape: "Без тела запроса.",
      responseShape: "Array<{ id, code, name, shortDescription }>",
      source: "Spring: ServiceController",
      notes: "Этот endpoint уже реально объявлен в backend и подходит для каталога услуг.",
    },
    {
      method: "POST",
      path: "/api/auth/register",
      access: "Public",
      status: "Implemented",
      purpose: "Регистрирует нового клиента.",
      requestShape: "{ fullName, email, phone, companyName, password }",
      responseShape: "boolean",
      source: "Spring: UsersController",
      notes:
        "Frontend после успешного boolean-ответа запрашивает /api/auth/me и сохраняет пользователя в локальное session-state.",
    },
    {
      method: "POST",
      path: "/api/auth/login",
      access: "Public",
      status: "Implemented",
      purpose: "Логинит пользователя и кладёт userId/userRole в HttpSession.",
      requestShape: "{ email, password }",
      responseShape: "boolean",
      source: "Spring: UserLoginController",
      notes: "По архитектуре это session-based auth на cookies + CSRF, без JWT/Bearer в frontend.",
    },
    {
      method: "POST",
      path: "/api/auth/account",
      access: "Session",
      status: "Implemented with issue",
      purpose: "Удаляет текущий аккаунт по userId из сессии.",
      requestShape: "Без тела запроса. Нужна активная серверная сессия.",
      responseShape: "void",
      source: "Spring: UserDelController",
      notes:
        "Текущий backend-контракт построен вокруг серверной сессии; frontend теперь тоже шлёт session-based POST-запрос.",
    },
  ];

  const PLANNED_API = [
    {
      method: "POST",
      path: "/api/client/applications",
      access: "Auth",
      status: "Planned",
      purpose: "Создание клиентской заявки с multipart-документами.",
      requestShape:
        "multipart/form-data: serviceCode, clientName, contact, companyName, description, documents[]",
      responseShape: "{ id, status, trackingCode }",
      source: "Frontend: orders-api.js",
      notes: "Нужен для формы отправки заявок с сайта.",
    },
    {
      method: "GET",
      path: "/api/client/orders",
      access: "Auth",
      status: "Planned",
      purpose: "Возвращает список заказов клиента в кабинете.",
      requestShape: "Без тела запроса.",
      responseShape: "Array<OrderSummary>",
      source: "Frontend: orders-api.js",
      notes: "Используется страницей личного кабинета.",
    },
    {
      method: "GET",
      path: "/api/client/orders/:orderId",
      access: "Auth",
      status: "Planned",
      purpose: "Возвращает карточку конкретного заказа.",
      requestShape: "orderId в path variable.",
      responseShape: "OrderDetails",
      source: "Frontend: orders-api.js",
      notes: "Нужен для `order.html`.",
    },
    {
      method: "POST",
      path: "/api/client/orders/:orderId/rework",
      access: "Auth",
      status: "Planned",
      purpose: "Отправляет заказ юристу на доработку с комментарием клиента.",
      requestShape: "{ comment }",
      responseShape: "OrderDetails или { success: true }",
      source: "Frontend: orders-api.js",
      notes: "Хороший кандидат на отдельный application service и историю статусов.",
    },
    {
      method: "PATCH",
      path: "/api/client/orders/:orderId",
      access: "Auth",
      status: "Planned",
      purpose: "Редактирует клиентскую заявку из карточки заказа.",
      requestShape: "{ serviceCode, clientName, contact, companyName, description }",
      responseShape: "OrderDetails | { success: true }",
      source: "Frontend: orders-api.js",
      notes: "Используется клиентской модалкой редактирования заявки.",
    },
    {
      method: "DELETE",
      path: "/api/client/orders/:orderId",
      access: "Auth",
      status: "Planned",
      purpose: "Удаляет клиентскую заявку после подтверждения.",
      requestShape: "Без тела запроса.",
      responseShape: "void | { success: true }",
      source: "Frontend: orders-api.js",
      notes: "После удаления frontend уводит пользователя обратно в кабинет.",
    },
    {
      method: "POST",
      path: "/api/auth/logout",
      access: "Auth",
      status: "Planned",
      purpose: "Завершает клиентскую сессию или инвалидирует refresh token.",
      requestShape: "Без тела запроса.",
      responseShape: "{ success: true }",
      source: "Frontend: auth-api.js",
      notes: "Если останешься на HttpSession, логично делать `session.invalidate()`.",
    },
    {
      method: "GET",
      path: "/api/auth/me",
      access: "Auth",
      status: "Planned",
      purpose: "Возвращает профиль текущего пользователя.",
      requestShape: "Без тела запроса.",
      responseShape: "{ id, fullName, email, phone, companyName, role }",
      source: "Frontend: auth-api.js",
      notes: "Аналог Spring Security `Principal`/`Authentication`-based endpoint.",
    },
    {
      method: "DELETE",
      path: "/api/auth/account",
      access: "Auth",
      status: "Planned",
      purpose: "Удаляет аккаунт в более REST-style контракте.",
      requestShape: "Без тела запроса.",
      responseShape: "{ success: true }",
      source: "Frontend: auth-api.js",
      notes: "Лучше совпадает с семантикой удаления ресурса.",
    },
    {
      method: "GET",
      path: "/api/staff/board/tasks",
      access: "Staff",
      status: "Planned",
      purpose: "Список задач для доски юриста.",
      requestShape: "Без тела запроса.",
      responseShape: "Array<TaskCard> | { items: TaskCard[] }",
      source: "Frontend: staff-api.js",
      notes: "Это уже будущий lawyer dashboard слой.",
    },
    {
      method: "GET",
      path: "/api/staff/board/tasks/:taskId",
      access: "Staff",
      status: "Planned",
      purpose: "Детали конкретной задачи на доске.",
      requestShape: "taskId в path variable.",
      responseShape: "TaskDetails",
      source: "Frontend: staff-api.js",
      notes: "Обычно это отдельный read-model endpoint.",
    },
    {
      method: "PATCH",
      path: "/api/staff/board/tasks/:taskId/status",
      access: "Staff",
      status: "Planned",
      purpose: "Меняет статус задачи на доске.",
      requestShape: "{ status }",
      responseShape: "TaskDetails",
      source: "Frontend: staff-api.js",
      notes: "По смыслу похож на update status command.",
    },
    {
      method: "PATCH",
      path: "/api/staff/board/tasks/:taskId",
      access: "Staff",
      status: "Planned",
      purpose: "Редактирует данные заявки с доски юриста.",
      requestShape: "{ serviceCode, clientName, contact, companyName, description }",
      responseShape: "TaskDetails",
      source: "Frontend: staff-api.js",
      notes: "Нужен для staff-модалки редактирования заявки.",
    },
    {
      method: "POST",
      path: "/api/staff/board/tasks/:taskId/reject",
      access: "Staff",
      status: "Planned",
      purpose: "Отклоняет заявку с обязательной причиной юриста.",
      requestShape: "{ reason }",
      responseShape: "TaskDetails | { success: true }",
      source: "Frontend: staff-api.js",
      notes: "После отклонения карточка исчезает из активных колонок доски.",
    },
    {
      method: "DELETE",
      path: "/api/staff/board/tasks/:taskId",
      access: "Staff",
      status: "Planned",
      purpose: "Удаляет заявку с доски юриста.",
      requestShape: "Без тела запроса.",
      responseShape: "void | { success: true }",
      source: "Frontend: staff-api.js",
      notes: "Используется staff-action удаления карточки.",
    },
    {
      method: "POST",
      path: "/api/staff/board/tasks/:taskId/comments",
      access: "Staff",
      status: "Planned",
      purpose: "Добавляет комментарий к задаче.",
      requestShape: "{ body }",
      responseShape: "TaskDetails",
      source: "Frontend: staff-api.js",
      notes: "Хорошо ложится на отдельную сущность comment/history.",
    },
  ];

  global.API_CATALOG = {
    IMPLEMENTED_API,
    PLANNED_API,
    API_SUMMARY: {
      implementedCount: IMPLEMENTED_API.length,
      plannedCount: PLANNED_API.length,
      backendStyle: "Сейчас backend ближе к HttpSession-подходу.",
      frontendStyle: "Фронт выровнен под HttpSession/cookie auth и ожидает более широкий прикладной API.",
    },
  };
})(window);
